#!/usr/bin/env node
// Generated by CoffeeScript 1.9.3
var argv, fs, path, prefix;

fs = require('fs');

path = require('path');

argv = require('yargs').usage('Usage: $0 --deps --dev-deps [path to package (defaults to ./)]').boolean('dev').describe('dev', 'also output dev dependencies').help('h').alias('h', 'help').argv;

prefix = "./";

if (argv._.length === 1) {
  prefix = argv[0];
}

fs.readFile(path.join(prefix, 'package.json'), 'utf-8', function(e, res) {
  var json, p, ref, ref1, results, v;
  json = JSON.parse(res);
  ref = json.dependencies;
  for (p in ref) {
    v = ref[p];
    console.log("%s@%s", p, v);
  }
  if (argv.dev) {
    ref1 = json.devDependencies;
    results = [];
    for (p in ref1) {
      v = ref1[p];
      results.push(console.log("%s@%s", p, v));
    }
    return results;
  }
});
